global:
  resolve_timeout: 5m

route:
  receiver: telegram
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: telegram
    webhook_configs:
      - url: "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage"
        send_resolved: true
        http_config:
          headers:
            Content-Type: "application/json"
        body: |
          {
            "chat_id": "${TELEGRAM_CHAT_ID}",
            "text": "⚠️ {{ .Status }} alert: {{ .CommonAnnotations.summary }}\n\n{{ .CommonAnnotations.description }}"
          }
