global:
  resolve_timeout: 5m

route:
  receiver: telegram
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: telegram
    webhook_configs:
      - url: "http://telegram-bot:8080"
        send_resolved: true