services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15.1
    container_name: wg-easy.15.1
    volumes:
      - ./data/:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - INIT_ENABLED=true
      - INIT_HOST=0.0.0.0
      - INIT_PORT=51820
      - DISABLE_IPV6=true
      - INIT_USERNAME=lephuhung77@gmail.com
      - INIT_PASSWORD=Galaxynote8@
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    environment:
      - TELEGRAM_BOT_TOKEN=7220335549:AAHKnCVnoqKnUc5vS1bhyX_UXDxCM5-Z5Mo
      - TELEGRAM_CHAT_ID=957114598
    restart: unless-stopped
    networks:
      - wg

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

networks:
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24
        - subnet: fdcc:ad94:bacf:61a3::/64

# folders should be generated inside container
volumes:
  grafana-storage:
  temp:
    driver: local
  temp1:
    driver: local
