version: "3.8"

services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:14.0.0
    container_name: wg-easy
    environment:
      - WG_HOST=109.123.232.186
      - PASSWORD_HASH='$$2a$12$qY1RksCo6D2MYw0sRnJhU.pUmC9w8T8YmSrF59AMPYatOXYp7.iGy'
      - WG_ALLOWED_IPS=10.10.0.0/24,10.8.0.0/24
      - WG_DEFAULT_DNS=10.10.0.48
      - WG_LISTEN_PORT=51820
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    volumes:
      - ./wireguard:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    labels:
      - "prometheus.job=wireguard"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx-prometheus-auth
    depends_on:
      - prometheus
    ports:
      - "9091:80"
    volumes:
      - ./nginx/prometheus.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    restart: unless-stopped

volumes:
  grafana-storage:
