rule_files:
  - "alert.rules.yml"
scrape_configs:
  - job_name: 'wg-easy'
    scrape_interval: 30s
    metrics_path: /metrics/prometheus
    static_configs:
        - targets:
          - 'vpn.hypersofts.vn'
    authorization:
      type: Bearer
      credentials: 'SuperSecurePassword'
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager.hypersofts.vn']

